FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.RHI" = "*", Win32 = "*", "Win32.WinPixEventRuntime" = "*"}

[Project]
Name = "Sedulous.RHI.DirectX12"
TargetType = "BeefLib"
StartupObject = "Sedulous.RHI.DirectX12.Program"
