FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.GAL" = "*", "Sedulous.OpenGLBindings" = "*"}

[Project]
Name = "Sedulous.GAL.OpenGL"
TargetType = "BeefLib"
StartupObject = "Sedulous.GAL.OpenGL.Program"
