FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.GAL" = "*", Bulkan = "*", "Sedulous.GAL.Android" = "*"}

[Project]
Name = "Sedulous.GAL.VK"
TargetType = "BeefLib"
StartupObject = "Sedulous.GAL.VK.Program"
ProcessorMacros = ["VALIDATE_USAGE"]
