FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Platform.Desktop" = "*", "Sedulous.RHI" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.ShaderCompiler" = "*"}

[Project]
Name = "RHI"
StartupObject = "RHI.Program"
