FileVersion = 1
Dependencies = {corlib = "*", Bulkan = "*", "Sedulous.Renderer" = "*", "Sedulous.Foundation" = "*", "Sedulous.Renderer.SPIRV" = "*", "Bulkan.Utilities" = "*"}

[Project]
Name = "Sedulous.Renderer.VK"
TargetType = "BeefLib"
StartupObject = "Sedulous.Renderer.VK.Program"
