FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Core" = "*", "Sedulous.RHI" = "*", "Sedulous.Platform" = "*", "Sedulous.SceneGraph" = "*"}

[Project]
Name = "Sedulous.Graphics"
TargetType = "BeefLib"
StartupObject = "Sedulous.Graphics.Program"
