FileVersion = 1
Dependencies = {corlib = "*", Bulkan = "*", "Sedulous.Foundation" = "*", "Sedulous.RHI" = "*"}

[Project]
Name = "Sedulous.RHI.Vulkan"
TargetType = "BeefLib"
StartupObject = "Sedulous.RHI.Vulkan.Program"
