FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Core" = "*", "Sedulous.SDL" = "*", "Sedulous.NRI.D3D12" = "*", "Sedulous.NRI.Vulkan" = "*", "Sedulous.NRI.Validation" = "*", "Sedulous.Graphics" = "*"}

[Project]
Name = "Sedulous.Sandbox"
StartupObject = "Sedulous.Sandbox.Program"
