FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.GAL" = "*", Win32 = "*"}

[Project]
Name = "Sedulous.GAL.D3D11"
TargetType = "BeefLib"
StartupObject = "Sedulous.GAL.D3D11.Program"
