FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Audio" = "*", OpenALNative = "*"}

[Project]
Name = "Sedulous.Audio.OpenAL"
TargetType = "BeefLib"
StartupObject = "Sedulous.Audio.OpenAL.Program"
