FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.MetalBindings" = "*", "Sedulous.GAL" = "*"}

[Project]
Name = "Sedulous.GAL.MTL"
TargetType = "BeefLib"
StartupObject = "Sedulous.GAL.MTL.Program"
